name: Shell Commands

on:
  - push

jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiple cmd script
        run: |
          node -v
          npm -v
