name: Shell Commands

on:
  - push

jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiple cmd script
        run: |
          node -v
          npm -v
  run-python-cmd:
    runs-on: ubuntu-latest
    needs:
      - run-shell-cmd
    steps:
      - name: python command
        run: |
          a = 3 + 2
          print('Ovo je python', a)
        shell: python
